version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Define the Python version and dependencies
python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt

# Build settings
build:
  os: ubuntu-20.04
  tools:
    python: "3.8"

# Enable server-side search
search:
  index: true
  ignore:
    - "*.log"
    - "*.tmp"